<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTpt0Mup\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTpt0Mup/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTpt0Mup.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTpt0Mup\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTpt0Mup\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tpt0Mup',
    'container.build_id' => 'f8735b16',
    'container.build_time' => 1673536757,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTpt0Mup');
