<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSCDJ6w0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSCDJ6w0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSCDJ6w0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSCDJ6w0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSCDJ6w0\App_KernelDevDebugContainer([
    'container.build_hash' => 'SCDJ6w0',
    'container.build_id' => 'b3c0ae8b',
    'container.build_time' => 1673537659,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSCDJ6w0');
